### ISSUE TITLE
NTP Timestamping

### ISSUE THREAD

**Issue by petertodd** [chainpoint/whitepaper#6]
The Tierion Token Sale Whitepaper's Chainpoint section claims this happens via the `hash_id` field, but it's unclear how this data is actually validated. How exactly does `hash_id` prevent invalid timestamps?

**Comment by grempe** [comment]
This isn't a bug report or feature request so I would normally refer you to the following sources of detailed information on this topic:

* Our current white paper which covers this topic extensively, available at https://tokensale.tierion.com/whitepaper
* Our May 2017 blog post, which covers in quite some detail, our innovations with the usage of Random Beacons and the bracketing of timestamps at https://tierion.com/blog/chainpoint-innovations-in-blockchain-timestamp-proofs/

To address your question. We provide multiple sources of time in every Chainpoint 3.0 proof.

* We maintain accurate server time on using the NTP time sync service with careful selection of the upstream time service provider. Our servers are accurate within microseconds of stratum-2 NTP. Our NTP service provider maintains its own stratum-1 and stratum-0 service infrastructure. Our service provider has its own fleet of atomic clocks that provide the reference for their stratum-0.
* I measured the offset of one of our servers to demonstrate. It has a current `offset` from its peers of `9.845 µs (microseconds)` (you read that correctly, µs not milliseconds).

```
$ ntpq -n
ntpq> rv
associd=0 status=0615 leap_none, sync_ntp, 1 event, clock_sync,
version="ntpd 4.2.8p4@1.3265-o Wed Jun 28 18:08:12 UTC 2017 (1)",
processor="x86_64", system="Linux/4.8.0-56-generic", leap=00, stratum=3,
precision=-24, rootdelay=1.452, rootdisp=38.509, refid=169.254.169.254,
reftime=dd2699a3.e4e63894  Sat, Jul 29 2017  5:20:35.894,
clock=dd269f8b.e56a0c40  Sat, Jul 29 2017  5:45:47.896, peer=1771, tc=10,
mintc=3, offset=0.009845, frequency=-0.462, sys_jitter=0.000000,
clk_jitter=0.030, clk_wander=0.002
```

* The premise of your question is biased. The statement that "hash_id prevent invalid timestamps"  doesn't really make a whole lot of sense. Our `hash_id` fields contain a version 1 UUID. Those UUIDs are just a container for an embedded timestamp provided by the system clock. The `hash_id` cannot *prevent* invalid timestamps as it *is itself a timestamp*. What we have said in the white paper is the following:

> Chainpoint solves this dilemma by including multiple trusted timestamps and multiple trust anchors in each proof. This allows Chainpoint proofs to simultaneously possess accurate and trustless time attestations.

Every fully completed Chainpoint 3.0 proof will contain the following representations of time. And every one of them is an integral part of the proof as its value is part of the hashing operations for that proof, inextricably embedded:

* The latest published NIST Beacon timestamp available (and its random value) prior to when a hash is submitted.
* The current NTP system time of the server receiving the hash in the form of a v1 UUID.
* The timestamp of the Calendar block (also from NTP), and NIST Beacon time is injected periodically as a block in the Calendar as well so that the Calendar itself is verifiable in time.
* The block data of the Ethereum block it is anchored to.
* The block data of the Bitcoin block it is anchored to.

Together, these multiple time values paint a picture of the time a hash was submitted. We don't want our users to be *required* to trust an NTP time that we provide, so we have taken careful effort to bracket it with publicly auditable timestamps that are outside of our control. We take great pains to ensure the accuracy of our NTP timestamp, and if you choose not to trust it implicitly that is ok, we don't blame you. We have always aimed for our service to be "trustless" in nature. In other words, we never want to say you need to "trust us" for any part of our proof, as almost every commercial timestamp authority I'm aware of currently does.

Clients who want to use the NTP derived timestamp can *easily* ensure that the time value included in the `hash_id` UUID is in fact accurate at the very moment of hash submission to us. All they have to do is extract the NTP server time from the UUID we give back to them in the POST response. Since our servers and Nodes are *extremely* fast in returning a UUID for a hash (single digit milliseconds are often observed) the client can trivially extract the time value out of the UUID at the moment they receive it and compare it to their own trusted local source of time for corroboration. If the two values are close enough for their individual comfort level, where close enough is probably partially determined by your network latency to our servers, they can have very high assurance that the timestamp is accurate at time of submission. This UUID is not only the handle used to retrieve a proof, it is carried with the hash and embedded into the proof in such a way that the time claim is verifiably and permanently part of the proof. This is the case since the UUID is actually SHA256 concatenated with the submitted hash as the very first operation in the proof. In other words:

* The UUID is a handle for retrieving a proof.
* The UUID is itself a precision timestamp; with a time extractable by anyone who sees it.
* The UUID is a source of random entropy, and is combined with hash to not only mix in the time, but to act as a cryptographic nonce, ensuring that even duplicate hashes are treated as unrelated throughout the aggregation and anchoring process.
* The UUID is returned immediately, and can be verified accurate, and easily, within perhaps 100 milliseconds or less of the submitter's local NTP clock depending on network latency.

We want our users to feel comfortable in trusting our precision timestamps are accurate. And what they can cryptographically *prove* is that our NTP time representing when a hash was submitted is *after* the NIST time, and it is provably *before* the creation of the Calendar block in our system, and the blocks on the public block chains we anchor to. This bracketed window of time is irrefutable. We [announced this innovation, and our cooperation with NIST this past May at the Consensus conference](https://tierion.com/blog/chainpoint-innovations-in-blockchain-timestamp-proofs/) knowing quite well that it provides a great deal of value to our proofs. This feature has been very well received by the community who have taken note that some existing services provide no timestamps in their proofs at all and have time granularity measured in hours or days instead of milliseconds or seconds. This is a powerful addition to their toolkit.

**Comment by grempe** [comment]
Closing. Unrelated to current repository, but question answered at length anyway.
