### ISSUE TITLE
Timestamp latency

### ISSUE THREAD

**Issue by petertodd** [chainpoint/whitepaper#7]
Apologies for opening a new issue, but @grempe blocked discussion on my previous one.

In https://github.com/chainpoint/whitepaper/issues/6 @grempe stated that:

> Since our servers and Nodes are extremely fast in returning a UUID for a hash (single digit milliseconds are often observed) the client can trivially extract the time value out of the UUID at the moment they receive it and compare it to their own trusted local source of time for corroboration.

By "extremely fast", what kind of latency can we expect in creating a new timestamp?

**Comment by grempe** [comment]
You seem to feel entitled to use our bug tracker, for an unrelated project repository, as your personal forum. I already answered your question in the quote from my previous response that you yourself provided:

> Since our servers and Nodes are extremely fast in returning a UUID for a hash (single digit milliseconds are often observed)

https://github.com/chainpoint/whitepaper/issues/6#issuecomment-318811705

Since you persist in asking me to answer a question you know has already been answered, I'll provide some more color.

I just submitted 1000  hashes, in 1000 individual requests, to our pre-production Core environment using 100 concurrent simulated users (BTW, our system also allows submitting 1000 hashes in every request, but I didn't use that functionality for this test). The entire test took `1844ms` to run and 99th percentile latency for those 1000 requests was `91ms`, 50th percentile was only `41ms`. Your mileage will of course vary depending on your connection to the network. There were zero non-200 responses. Each of those POST requests returned its own unique UUID with an embedded timestamp.

I've also run load tests with up to 10,000 concurrent users submitting multiple hashes as fast as they could with similar results. We are *very* performant when ingesting hashes and returning UUID's. For comparison, I've seen other projects that take ~1500ms just to process a single POST request to submit a single hash, and can't handle more than 50 hashes/sec in total. Our new systems are not only faster per request, but very wide in their ability to handle concurrent requests at scale. Our production environment is designed to scale far beyond that as needed, and that scaling can be accomplished quite easily by adding additional Kubernetes nodes to our production environment.

And of course, since users will submit hashes to a distributed set of Nodes instead of directly to Core we can scale to millions of hashes per second across the network as each Node performs its own Merkle tree aggregation every second.

I hope that finally satisfies your curiosity. You'll be able to try out these new systems in production soon. Please note, I will close all future issue tracker posts from you on topics unrelated to the repository at hand without comment.
